// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_task struct {
	*vcl.TForm
	Image1 *vcl.TImage

	// ::private::
	TFrm_taskFields
}

var Frm_task *TFrm_task

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_task)

func NewFrm_task(owner vcl.IComponent) (root *TFrm_task) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_task.gfm
var Frm_taskBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_task, &Frm_taskBytes)
