// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_main struct {
	*vcl.TForm
	Pnl_body *vcl.TPanel
	Sb_bar   *vcl.TStatusBar

	// ::private::
	TFrm_mainFields
}

var Frm_main *TFrm_main

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_main)

func NewFrm_main(owner vcl.IComponent) (root *TFrm_main) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_home.gfm
var Frm_mainBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_main, &Frm_mainBytes)
