// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"
	"github.com/ying32/govcl/vcl"
)

type TFrm_job_form struct {
	*vcl.TForm
	Edt_title       *vcl.TLabeledEdit
	Edt_cron        *vcl.TLabeledEdit
	Mmo_remarks     *vcl.TMemo
	Label1          *vcl.TLabel
	RB_01           *vcl.TRadioButton
	RB_02           *vcl.TRadioButton
	RB_03           *vcl.TRadioButton
	Label2          *vcl.TLabel
	Edt_script_path *vcl.TLabeledEdit
	Pnl_actions     *vcl.TPanel
	Btn_save        *vcl.TBitBtn
	Btn_cancel      *vcl.TBitBtn
	Od_select_path  *vcl.TOpenDialog
	IList           *vcl.TImageList

	// ::private::
	TFrm_job_formFields
}

var Frm_job_form *TFrm_job_form

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_job_form)

func NewFrm_job_form(owner vcl.IComponent) (root *TFrm_job_form) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed Frm_home_form.gfm
var Frm_job_formBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_job_form, &Frm_job_formBytes)
